// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYwDj9jtPeEr0fLWZnkBKnNwULIUDKBNM',
    appId: '1:360438673424:web:eece1ecd43bd49efdb5a95',
    messagingSenderId: '360438673424',
    projectId: 'my-test-app-18dcc',
    authDomain: 'my-test-app-18dcc.firebaseapp.com',
    storageBucket: 'my-test-app-18dcc.appspot.com',
    measurementId: 'G-JPZDFLCZML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnj-opQpgVDnKXIz11EMHaIrolu7uxu6M',
    appId: '1:360438673424:android:31ad553c8a2852b8db5a95',
    messagingSenderId: '360438673424',
    projectId: 'my-test-app-18dcc',
    storageBucket: 'my-test-app-18dcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApq1yBkhkwj9zBSBUHPQhth1gvVeQHV1E',
    appId: '1:360438673424:ios:53d65594fc5c6c2edb5a95',
    messagingSenderId: '360438673424',
    projectId: 'my-test-app-18dcc',
    storageBucket: 'my-test-app-18dcc.appspot.com',
    iosBundleId: 'com.example.recipiApp',
  );
}
